- id: csharpier
  name: Run CSharpier on C# files
  description: CSharpier is an opinionated C# formatter inspired by Prettier.
  stages: 
    - pre-commit
    - pre-merge-commit
    - pre-push
    - manual
  types:
    - c#
  language: python
  entry: csharpier
