#!/usr/bin/env sh

# Set good defaults to allow script to be run by hand. The three variables below
# will be overriden when run from within the workflow.
DOCKER_REPO=${DOCKER_REPO:-"gpsgate/csharpier"}
SOURCE_COMMIT=${SOURCE_COMMIT:-$(git log --no-decorate|grep '^commit'|head -n 1| awk '{print $2}')}
PLATFORMS=${PLATFORMS:-"linux/amd64"}

# Minimum version of csharpier to build for.
MINVER=${MINVER:-0.18.0}

# You shouldn't really need to have to modify the following variables.
GH_PROJECT=belav/csharpier
BUILDX_OPERATION=${BUILDX_OPERATION:-"--push"};   # Change to --load to build only.

# shellcheck disable=SC1091
. "$(dirname "$0")/reg-tags/image_api.sh"

# Login at the Docker hub to be able to access info about the image.
token=$(img_auth "$DOCKER_REPO")

_releases() {
  # Ask GH for the list of releases matching the tag pattern, then fool the sort
  # -V option to properly understand semantic versioning. Arrange for latest
  # version to be at the top. See: https://stackoverflow.com/a/40391207
  github_releases -r 'v?[0-9]+\.[0-9]+\.[0-9]+' "$1" |
    sed '/-/!{s/$/_/}' |
    sort -Vr |
    sed 's/_$//'
}

echo "============== Gettings latest releases for $GH_PROJECT at github"
_latest=
for tag in $(_releases "$GH_PROJECT"); do
  # Latest is the first tag that we encounter.
  if [ -z "$_latest" ]; then
    _latest="$tag"
  fi

  if [ "$(img_version "${tag#v}")" -ge "$(img_version "$MINVER")" ]; then
    # Get the revision out of the org.opencontainers.image.revision label, this
    # will be the label where we store information about this repo (it cannot be
    # the tag, since we tag as the base image).
    revision=$(img_labels --verbose --token "$token" -- "$DOCKER_REPO" "$tag" |
                grep "^org.opencontainers.image.revision" |
                sed -E 's/^org.opencontainers.image.revision=(.+)/\1/')
    # If the revision is different from the source commit (including empty,
    # which will happen when our version of the image does not already exist),
    # build the image, making sure we label with the git commit sha at the
    # org.opencontainers.image.revision OCI label, but using the same tag as the
    # library image.
    if [ "$revision" != "$SOURCE_COMMIT" ]; then
      echo "============== No ${DOCKER_REPO}:$tag at $SOURCE_COMMIT"
      # Prepare arguments for docker buildx.
      set -- \
        --tag "${DOCKER_REPO}:$tag" \
        --platform "$PLATFORMS" \
        --build-arg CSHARPIER_VERSION="$tag" \
        --label "org.opencontainers.image.revision=$SOURCE_COMMIT" \
        $BUILDX_OPERATION
      # Add latest tag when relevant
      if [ "$tag" = "$_latest" ]; then
        set -- \
          --tag "${DOCKER_REPO}:latest" \
          "$@"
      fi
      # Fix dotnet version, migrate to LTS 8.0 starting from 0.26.2. See:
      # https://github.com/belav/csharpier/releases/tag/0.26.2
      if [ "$(img_version "${tag#v}")" -ge "$(img_version "0.26.2")" ]; then
        set -- \
          --build-arg DOTNET_VERSION="8.0" \
          "$@"
      fi
      # build (and push) according to arguments and at the right tags.
      docker buildx build "$@" .
    fi
  fi
done