name: csharpier

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
      - 'main'
  schedule:
    # Midnight on Sunday and Wednesday
    - cron: "0 0 * * 0,3"

jobs:
  csharpier:
    runs-on: ubuntu-24.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      -
        name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: image=moby/buildkit:master
          platforms: linux/arm64,linux/amd64
      -
        name: Build and Push GHCR images
        env:
          DOCKER_REPO: ghcr.io/${{ github.repository }}
          SOURCE_COMMIT: ${{ github.sha }}
          PLATFORMS: ${{ steps.buildx.outputs.platforms }}
          LABEL_AUTHOR: Emmanuel Frécon <efrecon+github@gmail.com>
          LABEL_URL: ${{ github.server_url }}/${{ github.repository }}
          LABEL_DESCRIPTION: CSharpier is an opinionated code formatter for c#
          LABEL_TITLE: ${{ github.repository }}
        run: ./hooks/build+push
