name: csharpier

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
  schedule:
      - cron: "0 0 * * *"

jobs:
  csharpier:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      -
        name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build GHCR images
        env:
          DOCKER_REPO: ghcr.io/${{ github.repository }}
          SOURCE_COMMIT: ${{ github.sha }}
        run: ./hooks/build
      -
        name: Push GHCR images
        env:
          DOCKER_REPO: ghcr.io/${{ github.repository }}
          SOURCE_COMMIT: ${{ github.sha }}
        run: ./hooks/push